In [3]:
import numpy as np
np.random.seed(0)

In [21]:
X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]

In [25]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
        
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [26]:
layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

[[-0.07737703  0.26178541 -0.01730763  1.06078841 -0.22441858]
 [ 0.21302512  0.48972887  0.44337807  0.60477628 -0.16447573]
 [-0.38068997 -0.01416922  0.31981989  1.64769635  0.29721435]]


In [28]:
layer1.forward(X)

layer2.forward(layer1.output)
print(layer2.output)

[[ 0.05607434 -0.06939403]
 [ 0.07498651 -0.02973269]
 [-0.004129   -0.19636169]]
